//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMdicalIformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientMdicalIformation()
        {
            this.CustomerReturnVisit = new HashSet<CustomerReturnVisit>();
        }
    
        public int ConclusionID { get; set; }
        public int DoctorID { get; set; }
        public int CustomerAppointmentID { get; set; }
        public int SurgicalExaminationID { get; set; }
        public int MedicalExaminationID { get; set; }
        public Nullable<System.DateTime> InspectionTime { get; set; }
        public string InspectionResults { get; set; }
        public string ConclusionOfPhysicalExamination { get; set; }
    
        public virtual CustomerAppointment CustomerAppointment { get; set; }
        public virtual UserDoctorList UserDoctorList { get; set; }
        public virtual MedicalExamination MedicalExamination { get; set; }
        public virtual SurgicalExamination SurgicalExamination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReturnVisit> CustomerReturnVisit { get; set; }
    }
}
