//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAppointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerAppointment()
        {
            this.ClientMdicalIformation = new HashSet<ClientMdicalIformation>();
        }
    
        public int CustomerAppointmentID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string startTime { get; set; }
        public string EndTime { get; set; }
        public string PhysicalExaminationDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMdicalIformation> ClientMdicalIformation { get; set; }
        public virtual CustomerInformation CustomerInformation { get; set; }
    }
}
