//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReturnVisit
    {
        public int ContentID { get; set; }
        public int DoctorID { get; set; }
        public int ConclusionID { get; set; }
        public string ContentOfReturnVisit { get; set; }
        public System.DateTime ContentTime { get; set; }
    
        public virtual ClientMdicalIformation ClientMdicalIformation { get; set; }
        public virtual UserDoctorList UserDoctorList { get; set; }
    }
}
