//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KangmeiHospitalCRMEntities : DbContext
    {
        public KangmeiHospitalCRMEntities()
            : base("name=KangmeiHospitalCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientMdicalIformation> ClientMdicalIformation { get; set; }
        public virtual DbSet<CustomerAppointment> CustomerAppointment { get; set; }
        public virtual DbSet<CustomerInformation> CustomerInformation { get; set; }
        public virtual DbSet<CustomerReturnVisit> CustomerReturnVisit { get; set; }
        public virtual DbSet<CustomerService> CustomerService { get; set; }
        public virtual DbSet<KnowledgeBaseContentManagement> KnowledgeBaseContentManagement { get; set; }
        public virtual DbSet<KnowledgeBaseTypeManagement> KnowledgeBaseTypeManagement { get; set; }
        public virtual DbSet<MedicalExamination> MedicalExamination { get; set; }
        public virtual DbSet<MedicalHistory> MedicalHistory { get; set; }
        public virtual DbSet<SurgicalExamination> SurgicalExamination { get; set; }
        public virtual DbSet<UserDoctorList> UserDoctorList { get; set; }
    }
}
