//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalExamination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalExamination()
        {
            this.ClientMdicalIformation = new HashSet<ClientMdicalIformation>();
        }
    
        public int MedicalExaminationID { get; set; }
        public string BloodPressure { get; set; }
        public string Pulse { get; set; }
        public string DevelopmentAndNutrition { get; set; }
        public string HeartAndBloodVessels { get; set; }
        public string NervesAndSpirits { get; set; }
        public string LungAndRespiratoryTract { get; set; }
        public string AbdominalOrgan { get; set; }
        public string Liver { get; set; }
        public string Spleen { get; set; }
        public string Transaminase { get; set; }
        public string TransaminaseDescription { get; set; }
        public string HepatitisBSurfaceAntigen { get; set; }
        public string HepatitisBSurfaceAntigenDescription { get; set; }
        public string ChestXRay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMdicalIformation> ClientMdicalIformation { get; set; }
    }
}
