//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgicalExamination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurgicalExamination()
        {
            this.ClientMdicalIformation = new HashSet<ClientMdicalIformation>();
        }
    
        public int SurgicalExaminationID { get; set; }
        public string Height { get; set; }
        public string Bust { get; set; }
        public string Skin { get; set; }
        public string Weights { get; set; }
        public string PoorBreath { get; set; }
        public string Face { get; set; }
        public string Neck { get; set; }
        public string Spine { get; set; }
        public string Limb { get; set; }
        public string Joint { get; set; }
        public string Other { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMdicalIformation> ClientMdicalIformation { get; set; }
    }
}
